spring:
  application:
    name: cubic-backend
  #   DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/jsapi?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: JS
    password: JS285699
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 111.230.49.155
    database: 0
    password: JS285699
  mail:
    host: smtp.qq.com
    username:
    password:
    emailFrom:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
      eager: true                                     # 规则类型（flow/degrade/system/param-flow）
      datasource:
        flow-rule:
          nacos:
            server-addr: localhost:8848                           # Nacos地址（例: 127.0.0.1:8848）
            groupId: SENTINEL_GROUP                              # 分组名
            dataId: ${spring.application.name}-flow-rules         # 配置ID（建议应用名+规则类型）
            data-type: json                                       # 规则格式
            rule-type: flow
cos:
  client:
    accessKey:
    secretKey:
    region:
    bucket:
    cos-host: https://cos.website-of-js.cn
server:
  port: 7529
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
cubic:
  gatewayHost: https://api-gateway.website-of-js.cn
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://10.1.24.5:8848